### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by cwarner523** [halo123u/Art-store#1]
Writing the controllers, and models into one object makes the code a lot easier to 
read and makes the code more compact and simpler to navigate through. The names of
the items models describe what action is actually taking place so it is easy to
automatically know what is going on in the database. The whole project is organized
very effectively and easy to navigate through. The only thing that might help to
be more organized is in the ejs files to better space and format the divs and 
classes to know how they are being categorized and displayed. Overall great job, and good styling !!!!!!!!!!!!!!

**Comment by halo123u** [comment]
thanks i fixed the spacing. It was pretty bad!!
